// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlirdT6V9WQDqYX8uTQTmGt3wuoBY37uE',
    appId: '1:836742468141:web:c29d792949cf81c854dea4',
    messagingSenderId: '836742468141',
    projectId: 'todo-list-flutter-dd94d',
    authDomain: 'todo-list-flutter-dd94d.firebaseapp.com',
    storageBucket: 'todo-list-flutter-dd94d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXux_QB6fNoKTqNiqMSiPNC3jmlAM0ku4',
    appId: '1:836742468141:android:933c11863950960554dea4',
    messagingSenderId: '836742468141',
    projectId: 'todo-list-flutter-dd94d',
    storageBucket: 'todo-list-flutter-dd94d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6dTBpkC4_28o2fI0FViF18Of76LIMhJ8',
    appId: '1:836742468141:ios:3127ab179aee998054dea4',
    messagingSenderId: '836742468141',
    projectId: 'todo-list-flutter-dd94d',
    storageBucket: 'todo-list-flutter-dd94d.appspot.com',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6dTBpkC4_28o2fI0FViF18Of76LIMhJ8',
    appId: '1:836742468141:ios:3127ab179aee998054dea4',
    messagingSenderId: '836742468141',
    projectId: 'todo-list-flutter-dd94d',
    storageBucket: 'todo-list-flutter-dd94d.appspot.com',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlirdT6V9WQDqYX8uTQTmGt3wuoBY37uE',
    appId: '1:836742468141:web:1f6541203add4c7254dea4',
    messagingSenderId: '836742468141',
    projectId: 'todo-list-flutter-dd94d',
    authDomain: 'todo-list-flutter-dd94d.firebaseapp.com',
    storageBucket: 'todo-list-flutter-dd94d.appspot.com',
  );
}
